### ISSUE TITLE
v2: (and at least EDGE) queries for index.tag "link" behave different than queries for index.tag "page"

### ISSUE THREAD

**Issue by zeus-web** [silverbulletmd/silverbullet#1331]
I try to get a list of pages which links to specific pages.

So I created this query:

```
${query[[
   from index.tag "link" 
   select {FROM = "[[" .. page .. "|" .. page .. "]]", TO = toPage, }
   order by toPage
]]}
```

That works basically, the table looks ok. Strange is, the **order is different** between EDGE and v2.

**My main problem, though:**

I only want to see specific pages, so I tried this:
```
${query[[
   from index.tag "link" 
   where toPage:startsWith("Journal")
   select {VON = "[[" .. page .. "|" .. page .. "]]", ZU = toPage, }
   order by toPage
]]}
```
That fails, I get an LUA error: "Attempting to cal nil as a function".

so I tried this:
```
${query[[
   from index.tag "link" 
   where string.startsWith(toPage,"Journal")
   select {VON = "[[" .. page .. "|" .. page .. "]]", ZU = toPage, }
   order by toPage
]]}
```
That fails also, this time with LUA error "A.startsWith is not a function".

I tried similar (but with other fields) with `from index.tag "page"` which works like a charm...

**Comment by zefhemel** [comment]
Ok I finally got around to trying this and cannot reproduce the problem. As to the different sorting order between Edge and v2 — not sure about that, perhaps on edge the fields in `order by` assumed to be the ones you select, whereas in v2 this is no longer the case. For me it seems to correctly sort.

As to the other errors, I cannot reproduce them. I just get results.

Since I fixed a bunch of stuff since you reported this ticket, I'll assume somewhere along the line I fixed it. If not let me know and we can reopen and dig deeper.

**Comment by zeus-web** [comment]
Thanks for digging into it, zef. Unfortunately my main issue above is still existing...
I'm working on the latest edge (just updated to v2.0.0-pre4-16).

The issue seems to be with the "startsWith" function. That does work with different fields like "ref", "snippet", but not on other fields like "toPage" (using the query for "link" for example). 
This is not limited to the "link" query, I observed similar on other queries, too. However, it's not the same fields every time.

Investigating further, I suspect, it depends on the actual query results. It seems, that the result does not contain the same fields for every line. So I think, the command fails completely, as soon as the result has a line, where e.g. the field "toPage" is missing (or does contain anything else but a string), the error "Attempting to call nil as a function" is shown. 
And thinking about it, it is clear: if the field is not existing or does not contain a string (so e.g. a table), the "startsWith" function is not there, because without a string-field there is no string it could attach to...

However, I would like the query not to break, but just ignore the error and continue with the next result. 
Is there a way to tell the where clause to run only on existing fields?

Neither
`where toPage != null and toPage:startsWith("Jour")` 
nor `where toPage != nil and toPage:startsWith("Jour")` 
or `where toPage and toPage:startsWith("Jour")` 
does the trick...

Also I tried to get only results where toPage is a string with 
`where type(toPage) == "string" and toPage:startsWith("J")`
but got also the same "Attempting to call nil as a function" Error.

Maybe I`m on the wrong route, anyway...

Only I wonder, why you could not reproduce that on your end. I have the same issue on different systems, too... What is the difference?

**Comment by adxsoft** [comment]
I have version 2.4.1 and get exactly the same error with the where clause when doing a toPage:match function. This worked without resorting to Space Lua

${query[[
   from index.tag "link" 
   where type(toPage) == 'string' and toPage:match(".*%d%d%d%d%-%d%d%-%d%d$")
   select {FROM = "[[" .. page .. "|" .. page .. "]]", TO = toPage, }
   order by toPage
   limit 10
]]}
